### ISSUE TITLE
Basal rates

### ISSUE THREAD

**Issue by liroyvh** [skalahonza/TidepoolToNightScoutSync#1]
Hi!

Nice work =)
Are there any plans to import the basal rates from TP? :)

**Comment by skalahonza** [comment]
Hi,

Yesterday I finally finished my exams, which consumed most of my time. I will try to look at it. It is definitely a good idea.

**Comment by liroyvh** [comment]
> Hi,
> 
> Yesterday I finally finished my exams, which consumed most of my time. I will try to look at it. It is definitely a good idea.

Hope you finished them with a good result! :)

**Comment by skalahonza** [comment]
# Status update:
I contacted people from Tidepool and they provided me with some sample basal data, I am now thinking how to handle two scenarios:
1. static basal profile
2. basal corrections made by closed loop pumps (e.g. Tandem)

I think I will start with syncing basic basal profile into Nightscout before moving onto syncing basal corrections.

**Comment by liroyvh** [comment]
> # Status update:
> 
> I contacted people from Tidepool and they provided me with some sample basal data, I am now thinking how to handle two scenarios:
> 
> 1. static basal profile

Q: does that account for changes to the profile? Let's say you have 3 basal profiles in the pump and you switch a few times a week. Does the sync to nightscout account for that? Or just copy/paste the profile so to say? :)

**Comment by skalahonza** [comment]
Yes, I can see that Tidepool is aware of multiple profiles. Even the **activeSchedule** tells which one is active. So I just need to figure out, how to sync those profiles into Nightscout and properly select the active one.

```
    {
        "activeSchedule": "Chill",
        "automatedDelivery": true,
        "basalSchedules": {
            "Chill": [
                {
                    "rate": 0.65,
                    "start": 0
                },
                {
                    "rate": 0.7,
                    "start": 14400000
                },
                {
                    "rate": 0.725,
                    "start": 28800000
                },
                {
                    "rate": 0.6,
                    "start": 43200000
                },
                {
                    "rate": 0.6,
                    "start": 57600000
                },
                {
                    "rate": 0.675,
                    "start": 72000000
                },
                {
                    "rate": 0.6,
                    "start": 79200000
                }
            ],
            "Default": [
                {
                    "rate": 0.75,
                    "start": 0
                },
                {
                    "rate": 0.7,
                    "start": 3600000
                },
                {
                    "rate": 0.65,
                    "start": 7200000
                },
                {
                    "rate": 0.6,
                    "start": 10800000
                },
                {
                    "rate": 0.55,
                    "start": 14400000
                },
                {
                    "rate": 0.7,
                    "start": 21600000
                },
                {
                    "rate": 0.65,
                    "start": 36000000
                },
                {
                    "rate": 0.4,
                    "start": 61200000
                },
                {
                    "rate": 0.5,
                    "start": 64800000
                },
                {
                    "rate": 0.65,
                    "start": 68400000
                },
                {
                    "rate": 0.85,
                    "start": 72000000
                },
                {
                    "rate": 0.85,
                    "start": 81000000
                }
            ]
        }
}
```

**Comment by skalahonza** [comment]
I managed to sync basal profile into nightscout. I still have to do some testing tho. But it looks like it should work. 
![image](https://user-images.githubusercontent.com/13693312/126874810-a9ec38a7-9bfe-4a34-98a6-544fe53331b0.png)

**Comment by skalahonza** [comment]
@liroyvh 
I completed the feature. You can give it a try. 😊

**Comment by LiroyvH** [comment]
> @LiroyvH
> I completed the feature. You can give it a try. 😊

Hey sorry for the extremely slow response! 
That's really good news, thanks a lot!! I'll give it a try, probably this weekend :D, and let you know! :)

**Comment by LiroyvH** [comment]
@skalahonza One question: is it possible to *only* have it push data selectively? For example: if I want to *only* send the basal rate and not the bolus (as that would produce duplicate data), is that possible somehow? Couldn't find it in the README.

**Comment by skalahonza** [comment]
Hi, sorry for slow response on my side now 😄 
Right now it is not possible to select what you want to sync. The integration tries to minimize duplicities by comparing the date time of the event. For example, if there is an existing bolus at 15:00 it should not duplicate the data.

Now the integration only syncs basal profiles.
![image](https://user-images.githubusercontent.com/13693312/135589551-f4850c7c-b652-4ba5-913e-67b4dc133c65.png)
I didn't manage to handle temporary basal rates yet.

**Comment by panbroggi** [comment]
Hi! I am very interested in registering basal rate changes due to Tandem Control IQ. Do you think the feature will be included in this tool?

BTW, Thank you very much for this tool!
