### ISSUE TITLE
Combo bolus

### ISSUE THREAD

**Issue by XeelS** [skalahonza/TidepoolToNightScoutSync#3]
Hello!
First I'd like to thank you for creating this app!
Data collection and sharing is really complicated between all of the services we have at our disposition and this tool is a life saver for syncing the data from a TSlim X2 to NightScout!
However I've just noticed it doesn't seem to sync combo boluses (extended boluses on the X2).
Is it an issue from the Tidepool Uploader or from your tool not supporting that feature yet?

Thanks again for the time you spent creating it!

**Comment by XeelS** [comment]
Looking at the exported Excel file from Tidepool, it seems the Tidepool Updater supports reading the extended boluses from the X2.

**Comment by skalahonza** [comment]
Hello,

This will definitely be caused by the tool not supporting it. I will try to look at it. 
According to this issue, I would have to split combo bolus into two treatments. 
https://github.com/nightscout/cgm-remote-monitor/issues/1372

**Comment by skalahonza** [comment]
Ok. I managed to make some progress.
## Data from Tidepool
```js
{
        "clockDriftOffset": 0,
        "conversionOffset": 0,
        "deviceId": "tandemCIQ1002717664049",
        "deviceTime": "2021-08-20T19:43:18",
        "duration": 3600000,
        "extended": 3.35,
        "guid": "e39297e3-3123-4145-9080-1c4e5ee5db05",
        "id": "0saf5e2mmcgkj1fimrop8p1soe0e55p4",
        "normal": 1.65,
        "payload": {
            "logIndices": [
                290703
            ]
        },
        "subType": "dual/square",
        "time": "2021-08-20T23:43:18.000Z",
        "timezoneOffset": -240,
        "type": "bolus",
        "uploadId": "upid_dd0a49931113"
    }
```

## Data to Nightscout
```js
    {
        "created_at": "{{$timestamp}}",
        "enteredBy": "Tidepool",
        "eventType": "Combo Bolus",
        "insulin": 1.65,
        "duration": 60,
        "relative": 3.35
    }
```

## UI changes
![image](https://user-images.githubusercontent.com/13693312/150676123-118dfd75-229d-41ac-bc4b-be2415728fad.png)

**Comment by skalahonza** [comment]
Code merged, new release created: https://github.com/skalahonza/TidepoolToNightScoutSync/releases/tag/0.9.2

**Comment by skalahonza** [comment]
Hello @XeelS,

Did you have a chance to testi it? Also I would like to ask, how are you using this tool? Is it just for your own usage, or are more people involved (patients, doctors, etc)? I am gald that it helps other people, because this started as a small hobby project.
